### ISSUE TITLE
+ add node results in bad request

### ISSUE THREAD

**Issue by rezubuse** [mbarde/sloth-tools#7]
server output: [17/Jun/2022 22:58:09] "GET /node/create HTTP/1.1" 400 -
browser output: Bad Request - Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

Installed on Raspbian GNU/Linux 11 (bullseye) 
Happy to help with any debugging, but I don't have the skill to do it on my own.

**Comment by mbarde** [comment]
Hi, thank you for the report, should be fixed via https://github.com/mbarde/sloth-tools/commit/d303a851d232034cdd0c5ac47886452427f931cd - please test :)

**Comment by rezubuse** [comment]
Hello, adding nodes works fine now. 
Thanks for the quick fix :)

**Comment by rezubuse** [comment]
Hello, adding nodes works fine now.
Thanks for the quick fix :)
